fix Message.is_scheduled field always False when parsing UpdateNewScheduledMessage
hydrogram/hydrogram pull request #14
Opened 2023-12-20 19:05 UTC by wulan17

## Description

Because i put topics parameter before is_scheduled in Message._parse method, everytime client get UpdateNewScheduledMessage updates the is_scheduled field will always False
Add the parameter name fix the issue

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
I test using my private bot, before this fix everytime i scheduled a message the is_scheduled field always return False and after this fix its return True

### Test Configuration

- Operating System: Ubuntu 22.04
- Python Version: 3.10

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes

2023-12-20 23:54 UTC, alissonlauffer commented
Thank you for your contribution!
Well, I think it's better to just pass all `_parse` arguments as keyword-only, to avoid future breakage when we add new arguments there.
I'll push the needed changes to your PR.

2023-12-21 00:26 UTC, alissonlauffer approved these changes

2023-12-21 00:35 UTC, HitaloM requested changes
Thanks for the contribution, everything seems to be correct, the only thing missing is the news fragment for the changelog. @alissonlauffer could you do this?

2023-12-21 01:17 UTC, HitaloM approved these changes
Now it's complete, great work from both of you. 🫡

2024-01-16 04:09 UTC, merged